const DEFAULT_SCORE = 0;
const DEFAULT_BIRD_SCORE = 0;
const SCORE_STR_LENGTH = 4;
const BIRD_SCORE_STR_LENGTH = 2;

export {
  DEFAULT_SCORE,
  SCORE_STR_LENGTH,
  DEFAULT_BIRD_SCORE,
  BIRD_SCORE_STR_LENGTH,
};
